# Generated by Django 3.2.24 on 2024-07-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0191_product_lending'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='return_on_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
