# Generated by Django 3.2.24 on 2024-10-25 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0183_alter_order_number'),
        ('account', '0107_alter_user_options'),
        ('product', '0192_productvariant_return_on_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variant_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRODUCT_VARIANT CREATED', 'product_variant created'), ('PRODUCT_VARIANT UPDATED', 'product_variant updated'), ('PRODUCT_VARIANT DELETED', 'product_variant deleted')], max_length=255)),
                ('number', models.IntegerField(blank=True, default=saleor.product.models.get_balance_event_number, null=True)),
                ('stock_changed', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_events', to='order.order')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_events', to='product.productvariant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_events', to='account.user')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRODUCT_CREATED', 'product_created'), ('PRODUCT_DELETED', 'product_deleted')], max_length=255)),
                ('number', models.IntegerField(blank=True, default=saleor.product.models.get_balance_event_number, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='account.user')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
