# Generated by Django 3.2.24 on 2025-02-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0183_alter_order_number'),
        ('account', '0111_alter_user_balance'),
        ('product', '0194_auto_20250213_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantevent',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='type',
            field=models.CharField(choices=[('PRODUCT_CREATED', 'product_created'), ('PRODUCT_DELETED', 'product_deleted'), ('PRODUCT_UPDATED', 'product_updated')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariantevent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_events', to='order.order'),
        ),
        migrations.AlterField(
            model_name='productvariantevent',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_events', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantevent',
            name='product_variant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariantevent',
            name='type',
            field=models.CharField(choices=[('PRODUCT_VARIANT_CREATED', 'product_variant_created'), ('PRODUCT_VARIANT_UPDATED', 'product_variant_updated'), ('PRODUCT_VARIANT_DELETED', 'product_variant_deleted'), ('PRODUCT_VARIANT_PRICE_UPDATED', 'product_variant_price_updated'), ('PRODUCT_VARIANT_STOCK_CHANGED', 'product_variant_stock_changed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariantevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variant_events', to='account.user'),
        ),
    ]
