# Generated by Django 3.2.24 on 2025-02-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0195_auto_20250213_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productevent',
            name='number',
        ),
        migrations.RemoveField(
            model_name='productvariantevent',
            name='number',
        ),
    ]
