# Generated by Django 3.2.24 on 2024-04-03 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0087_alter_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(max_length=3)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
                'permissions': (('manage_donations', 'Manage donations'),),
            },
        ),
    ]
