# Generated by Django 3.2.24 on 2024-07-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='completed',
        ),
        migrations.AddField(
            model_name='donation',
            name='barcode',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, choices=[('unreviewed', 'The donation is not yet to be reviewed.'), ('completed', 'The donation is completed.'), ('rejected', 'The donation is rejected.')], default='unreviewed', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
