# Generated by Django 3.2.24 on 2024-07-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20240714_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='barcode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
