# Generated by Django 3.2.24 on 2024-07-17 15:28

from django.db import migrations, models
import saleor.donation.models


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0007_donation_number"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SEQUENCE donation_donation_number_seq OWNED BY donation_donation.number;

            SELECT setval('donation_donation_number_seq', coalesce(max(number), 0) + 1, false)
            FROM donation_donation;
        """
        ),
        migrations.AlterField(
            model_name="donation",
            name="number",
            field=models.IntegerField(
                blank=True,
                default=saleor.donation.models.get_donation_number,
                null=True,
                unique=True,
            ),
        ),
    ]
