# Generated by Django 3.2.24 on 2024-08-11 13:49

from django.db import migrations, models
import saleor.donation.models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_donation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='number',
            field=models.IntegerField(blank=True, default=saleor.donation.models.get_donation_number, null=True),
        ),
    ]
