# Generated by Django 3.2.24 on 2025-06-19 14:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.donation.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_donation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(default=saleor.donation.models.get_certificate_number, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('template_filename', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
                'permissions': (('manage_donations', 'Manage donations'),),
            },
        ),
        migrations.RunSQL(
            """
            CREATE SEQUENCE donation_certificate_number_seq OWNED BY donation_certificate.number;

            SELECT setval('donation_certificate_number_seq', coalesce(max(number), 0) + 1, false)
            FROM donation_certificate;
            """
        ),
        migrations.AddField(
            model_name='donation',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donation.certificate'),
        ),
    ]
