# Generated by Django 3.2.24 on 2024-06-11 14:33

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('site', '0040_sitesettings_allow_login_without_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='site.sitesettings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('users', models.PositiveIntegerField(default=0)),
                ('circulated_currency', models.PositiveBigIntegerField(default=0)),
                ('circulated_items', models.PositiveIntegerField(default=0)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteCarouselLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('url', models.TextField()),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='site.sitecarousel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sitestatistics',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='sitestatistics_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='sitestatistics',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='sitestatistics_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='sitecarouselline',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='sitecarouselline_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='sitecarouselline',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='sitecarouselline_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='sitecarousel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='sitecarousel_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='sitecarousel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='sitecarousel_meta_idx'),
        ),
    ]
