# Generated by Django 3.2.24 on 2024-06-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0041_auto_20240611_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecarouselline',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='site.sitecarousel'),
        ),
    ]
