# Generated by Django 3.2.24 on 2024-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0042_alter_sitecarouselline_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecarousel',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
