# Generated by Django 3.2.24 on 2026-02-12 11:54

from django.db import migrations, models
import saleor.site.models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0044_alter_sitecarousel_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestatistics',
            name='poor_users',
            field=models.PositiveIntegerField(default=saleor.site.models.get_default_poor_users),
        ),
    ]
