# Generated by Django 3.2.24 on 2024-06-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0062_update_checkout_last_transaction_modified_at_and_refundable'),
        ('warehouse', '0033_warehouse_external_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkout_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='checkout.checkoutline'),
        ),
    ]
