# Generated by Django 3.2.24 on 2024-06-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0182_alter_order_status'),
        ('warehouse', '0034_alter_reservation_checkout_line'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='warehouse_r_checkou_b66369_idx',
        ),
        migrations.AddField(
            model_name='reservation',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='order.orderline'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['order_line', 'reserved_until'], name='warehouse_r_order_l_e43d5b_idx'),
        ),
    ]
