# Generated by Django 3.2.24 on 2024-07-18 17:26

from django.db import migrations, models
import saleor.barcode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_month', models.IntegerField(default=2407, editable=False)),
                ('used', models.BooleanField(default=False)),
                ('sub', models.IntegerField(default=saleor.barcode.models.get_sub, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
