# Generated by Django 3.2.24 on 2024-07-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'ordering': ('-created_at',), 'permissions': (('manage_barcodes', 'Manage barcodes'),)},
        ),
    ]
