# Generated by Django 3.2.24 on 2024-08-05 15:19

from django.db import migrations, models
import saleor.barcode.models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0002_alter_barcode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='year_month',
            field=models.IntegerField(default=saleor.barcode.models.current_year_month, editable=False),
        ),
    ]
