# Generated by Django 3.2.24 on 2024-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_add_default_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
