# Generated by Django 3.2.24 on 2024-08-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_page_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetranslation',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
