# Generated by Django 3.2.24 on 2024-08-11 13:57

from django.db import migrations, models
import saleor.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0182_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=saleor.order.models.get_order_number, editable=False),
        ),
    ]
