# Generated by Django 3.2.24 on 2025-02-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0183_alter_order_number'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP SEQUENCE IF EXISTS order_order_number_seq;

            CREATE SEQUENCE order_order_number_seq OWNED BY order_order.number;

            SELECT setval('order_order_number_seq', coalesce(max(number), 0) + 1, false)
            FROM order_order
            WHERE DATE_TRUNC('month', created_at) = DATE_TRUNC('month', NOW());
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
