# Generated by Django 3.2.23 on 2024-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_merge_20231205_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=300),
        ),
    ]
