# Generated by Django 3.2.24 on 2024-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_auto_20240303_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
