# Generated by Django 3.2.24 on 2024-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='continuous',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
