# Generated by Django 3.2.24 on 2024-03-14 07:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_user_continuous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('300.0'), max_digits=12),
        ),
    ]
