# Generated by Django 3.2.24 on 2024-06-19 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_auto_20240619_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consecutive_logins',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='balanceevent',
            name='type',
            field=models.CharField(choices=[('DONATION_GRANTED', 'donation_granted'), ('FIRST_LOGIN', 'first_login'), ('MANUALLY_UPDATED', 'manually_updated'), ('CONSECUTIVE_LOGIN', 'consecutive_login'), ('CONSUMED', 'consumed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
