# Generated by Django 3.2.24 on 2024-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0093_alter_balanceevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceevent',
            name='delta',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
