# Generated by Django 3.2.24 on 2024-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_balanceevent_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceevent',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
