# Generated by Django 3.2.24 on 2024-07-21 08:06

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0095_balanceevent_number"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SEQUENCE account_balanceevent_number_seq OWNED BY account_balanceevent.number;

            SELECT setval('account_balanceevent_number_seq', coalesce(max(number), 0) + 1, false)
            FROM account_balanceevent;
        """
        ),
        migrations.AlterField(
            model_name="balanceevent",
            name="number",
            field=models.IntegerField(
                blank=True,
                default=saleor.account.models.get_balance_event_number,
                null=True,
            ),
        ),
    ]
