# Generated by Django 3.2.24 on 2024-08-15 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_alter_balanceevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('300.5'), max_digits=12),
        ),
    ]
