# Generated by Django 3.2.24 on 2024-09-10 08:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceevent',
            name='type',
            field=models.CharField(choices=[('DONATION_GRANTED', 'donation_granted'), ('DONATION_REJECTED', 'donation_rejected'), ('FIRST_LOGIN', 'first_login'), ('MANUALLY_UPDATED', 'manually_updated'), ('CONSECUTIVE_LOGIN', 'consecutive_login'), ('CONSUMED', 'consumed'), ('REFUNDED', 'refunded'), ('INVITE_NEW_USER', 'invite_new_user'), ('SPECIAL_EVENT', 'special_event'), ('BONUS', 'bonus'), ('POOR_SIGN', 'poor_sign'), ('OTHER', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('50.5'), max_digits=12),
        ),
    ]
