# Generated by Django 3.2.24 on 2024-09-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_alter_invitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceevent',
            name='type',
            field=models.CharField(choices=[('DONATION_GRANTED', 'donation_granted'), ('DONATION_REJECTED', 'donation_rejected'), ('FIRST_LOGIN', 'first_login'), ('MANUALLY_UPDATED', 'manually_updated'), ('CONSECUTIVE_LOGIN', 'consecutive_login'), ('CONSUMED', 'consumed'), ('REFUNDED', 'refunded'), ('INVITE_NEW_USER', 'invite_new_user'), ('SPECIAL_EVENT', 'special_event'), ('BONUS', 'bonus'), ('POOR_SIGN', 'poor_sign'), ('OTHER', 'other'), ('INVITATION_ACCEPTED', 'invitation_accepted')], max_length=255),
        ),
    ]
