# Generated by Django 3.2.24 on 2024-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0104_alter_balanceevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='code',
            field=models.CharField(db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
