# Generated by Django 3.2.24 on 2024-09-28 07:15

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0105_auto_20240928_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(db_index=True, default=saleor.account.models.generate_invitation_code, max_length=128, null=True, unique=True),
        ),
    ]
