# Generated by Django 3.2.24 on 2024-11-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0108_alter_balanceevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
