# Generated by Django 3.2.24 on 2024-11-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0109_user_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
