# Generated by Django 3.2.24 on 2025-02-13 10:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0110_user_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
