# Generated by Django 3.2.24 on 2025-03-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0111_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
