# Generated by Django 3.2.24 on 2025-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_user_graduate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='not_active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
