# Generated by Django 3.2.24 on 2025-04-17 11:49

from django.db import migrations, models
import saleor.csv.models


class Migration(migrations.Migration):
    dependencies = [
        ("csv", "0004_auto_20210709_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportfile",
            name="export_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exportfile",
            name="number",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.RunSQL(
            """
            DROP SEQUENCE IF EXISTS csv_exportfile_seq;
            CREATE SEQUENCE csv_exportfile_seq OWNED BY csv_exportfile.number;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
