# Generated by Django 3.2.24 on 2025-05-25 14:24

from django.db import migrations, models
import saleor.csv.models


class Migration(migrations.Migration):

    dependencies = [
        ('csv', '0005_auto_20250417_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='number',
            field=models.IntegerField(default=saleor.csv.models.get_export_number, null=True, unique=True),
        ),
    ]
