# Generated by Django 3.2.24 on 2026-02-09 07:21

from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer
import saleor.csv.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0113_user_not_active_until"),
        ("csv", "0006_alter_exportfile_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.IntegerField(
                        default=saleor.csv.models.get_import_number,
                        null=True,
                        unique=True,
                    ),
                ),
                ("data_file", models.FileField(null=True, upload_to="import_files")),
                (
                    "type",
                    models.CharField(
                        choices=[("account", "Account")],
                        default="account",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                ("message", models.CharField(max_length=255, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_files",
                        to="account.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            """
            DROP SEQUENCE IF EXISTS csv_importfile_seq;
            CREATE SEQUENCE csv_importfile_seq OWNED BY csv_importfile.number;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
