# Generated by Django 3.2.24 on 2026-02-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv', '0007_importfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
